### ISSUE TITLE
libyui-qt missing libyui dependency

### ISSUE THREAD

**Issue by anaselli** [libyui/libyui#10]
1. Downloaded libyui-qt from [Releases](https://github.com/libyui/libyui/releases/tag/libyui-qt%2F4.0.1)
2.  didn't install either libyui or libyui-devel
3. built libyui-qt

> make -f Makefile.repo 
> rm -rf build
> mkdir build; \
> cd build; \
> cmake ..
> -- The C compiler identification is GNU 10.2.1
> -- The CXX compiler identification is GNU 10.2.1
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: /usr/bin/cc - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: /usr/bin/c++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/anaselli/src/libyui/TEST/libyui-libyui-qt-4.0.1/libyui-qt/build
> 
> To build:
> 
>   cd build
>   make
> 
> [anaselli@gandalf libyui-qt]$ cd build/
> [anaselli@gandalf build]$ make
> Scanning dependencies of target local-include-dir
> [  0%] Built target local-include-dir
> Scanning dependencies of target libyui-qt_autogen
> [  1%] Automatic MOC and UIC for target libyui-qt
> [  1%] Built target libyui-qt_autogen
> [  2%] Automatic RCC for qt_icons.qrc
> Scanning dependencies of target libyui-qt
> [  4%] Building CXX object src/CMakeFiles/libyui-qt.dir/libyui-qt_autogen/mocs_compilation.cpp.o
> In file included from /home/anaselli/src/libyui/TEST/libyui-libyui-qt-4.0.1/libyui-qt/build/src/libyui-qt_autogen/EWIEGA46WW/moc_QY2DiskUsageList.cpp:10,
>                  from /home/anaselli/src/libyui/TEST/libyui-libyui-qt-4.0.1/libyui-qt/build/src/libyui-qt_autogen/mocs_compilation.cpp:4:
> /home/anaselli/src/libyui/TEST/libyui-libyui-qt-4.0.1/libyui-qt/build/src/libyui-qt_autogen/EWIEGA46WW/../../../../src/QY2DiskUsageList.h:32:10: fatal error: yui/FSize.h: File o directory non esistente
>    32 | #include <yui/FSize.h>
>       |          ^~~~~~~~~~~~~
> compilation terminated.
> make[2]: *** [src/CMakeFiles/libyui-qt.dir/build.make:117: src/CMakeFiles/libyui-qt.dir/libyui-qt_autogen/mocs_compilation.cpp.o] Errore 1
> make[1]: *** [CMakeFiles/Makefile2:143: src/CMakeFiles/libyui-qt.dir/all] Errore 2
> make: *** [Makefile:149: all] Errore 2

I would expect a check during configuration as it was before, find_library, find_program or something like that to add missing paths. 
If i install libyui builds correctly though.

**Comment by shundhammer** [comment]
Since we merged all the libyui core repos into one, the tarball is now self-contained: It contains all those subprojects. Of course you still have to build them in the correct order; this is what the new toplevel `build-all` script (merged yesterday) is all about. See also the updated [README.md](https://github.com/libyui/libyui/blob/master/README.md#building).

For RPM builds, the .spec files contain the necessary BuildRequires.
