### ISSUE TITLE
Example Project

### ISSUE THREAD

**Issue by UltraBlackLinux** [libyui/libyui#108]
Hey tehre,
for quite a while now I've been searching for a GTK gui library that is easy to use (not as much of a pain as plain gtk), easy to understand and doesn't require a weird setup.

I'd really appreciate an example project to see if this would make sense for me.

Thanks!

**Comment by shundhammer** [comment]
For examples, it's best to start with the examples subdirectory :smiley: :

https://github.com/libyui/libyui/tree/master/libyui/examples

Start with the classic _HelloWorld_.

https://github.com/libyui/libyui/blob/master/libyui/examples/HelloWorld.cc

...and then work your way through the other ones. They are all (or most?) one-source-file examples.


## YaST Widget Demo

This uses the Ruby bindings, but it can give you a quick overview over the available widgets:

![widget-demo-tw-01](https://user-images.githubusercontent.com/11538225/119511524-cbea8d80-bd72-11eb-9c92-81d63eff0085.png)

https://github.com/yast/yast-widget-demo

More screenshots: https://github.com/yast/yast-widget-demo/issues/2

More docs are linked from the widget demo main page.


## Caveat

libyui is not primarily a Gtk GUI library. The intent is to be independent of GUI vs. text mode (NCurses), and the primary GUI lib is Qt. The Gtk version is a purely community-driven project.

As a frontend-independent library, libyui comes with limitations: You cannot use the full power of the GUI lib. You are limited to what maps to NCurses as well. There are tradeoffs. But on the pro side, unless you really make an effort to sabotage it, you always get a text version as well.

If you want to do very fancy stuff making optimal use of all Gtk widgets, use Gtk directly.

Choose your poison. :smiley:

**Comment by UltraBlackLinux** [comment]
oh thank you! I completely missed that since it wasn't in the top level, my bad.
