### ISSUE TITLE
Question : Force TUI (ncurses)

### ISSUE THREAD

**Issue by VladStanimirOSF** [libyui/libyui#116]
I see on the documentation page that in order to force libYUI to use ncurses you are supposed to  precede the execution of the program with "unset DISPLAY;". Is there a way to force ncurses from within the program or to programmatic unset the display?

**Comment by jreidinger** [comment]
@VladStanimirOSF yes, it is possible. You can use `YUILoader::loadPlugin` method, which force loading specific plugin. In your case ncurses one. See https://github.com/libyui/libyui/blob/4e5dfa950cfab5185b0695b0576f1d1af1c85117/src/YUILoader.cc#L135 which is generic method to load UI, so you can instead use specific one which loads requested UI. Is it clear? If not feel free to ask or show your code.
Josef

**Comment by jreidinger** [comment]
Another option, maybe easier for you is to set env YUI_PREFERED_BACKEND before loading UI. see https://github.com/libyui/libyui/blob/4e5dfa950cfab5185b0695b0576f1d1af1c85117/src/YUILoader.cc#L47
It depends on your exact use case and what you want to achieve.

**Comment by VladStanimirOSF** [comment]
Tx.
I will give the methods a try, i have just started working on the application and learning to use the library last night so there is no code to show yet. If i have future question i will be sure to ask :smiley:
