### ISSUE TITLE
Enhancements request – Optimal use of the screen's surface.

### ISSUE THREAD

**Issue by Ricky-Tigg** [libyui/libyui#125]
_OS_: _Linux_ – _Fedora_ – _13.3-inched screen_ laptop – _1280 x 800 pix_ resolution – _Cantarell Regular 11_ interface font. – _Gnome_ environment.
_Component_: libyui.x86_64 3.3.3-1.fc28 @fedora
dnfdragora.noarch 1.0.1-10.git20180108.b0e8a66.fc28

_Actuals results_: At best, **nine lines are visible at once**. Since searches targeted to resources may produce consequent outputs an underlying optimization of the space used is needed. 

All optimisations would add to visible at once about **eleven new lines**. Following observations are related to that field (optimizations evaluation in lines are between signs  '–'):
– _1 line_ – Ability to expand the _Dnfdragora_ window to fully fill the screen (_key F11_).

– _4 lines_ – 
– **Icon illustrating application** –_Dnfdragora_– to be located on the left top corner (left side of '_File_') or 
– ability to **move horizontal separation bar** (here needed up) in the second following illustration.

![image](https://user-images.githubusercontent.com/26058215/40325611-bfb0bbb4-5d3c-11e8-9212-6804259a9ede.png)

– Ability to **move vertical separation bar** (here needed to the left).

![image](https://user-images.githubusercontent.com/26058215/40325638-de7d1650-5d3c-11e8-8bdc-c9b6e9fc8dc2.png)

– _6 lines_ – Ability to **move horizontal separation bar** (here needed down).

![image](https://user-images.githubusercontent.com/26058215/40325652-ed14b2a4-5d3c-11e8-9e4b-94f8f55d42ae.png)

– Ability to optimize above mentioned both vertical and horizontal separation bars' locations by _double-left-clicking_ the bar involved.
– **Automatic optimizations** of the use of spaces related to columns to be the **default behaviour**. For now optimizations rely on manual operations –_double-left-clicks_– (See respective _double-arrow_).

![image](https://user-images.githubusercontent.com/26058215/40325687-03c47a66-5d3d-11e8-89f9-4e237c783e7f.png)

**Comment by hellcp** [comment]
I will guess this is for libyui-gtk client. Please report against [libyui-gtk](https://github.com/libyui/libyui-gtk).
