### ISSUE TITLE
Column sort does not work for GTK

### ISSUE THREAD

**Issue by dalanicolai** [libyui/libyui#127]
While sorting by clicking column header does  work in dnfdragora --qt, it does NOT work in dnfdragora --gtk. I hope this is the right place to report since I read [here](https://github.com/manatools/dnfdragora/issues/48) that they should have the same behavior

**Comment by hellcp** [comment]
Please report bugs for libyui-gtk in [libyui-gtk](https://github.com/libyui/libyui-gtk) repository, it's easier to track it that way.

**Comment by shundhammer** [comment]
Sorry, this is the wrong place for that problem. As @hellcp wrote, plase report this at the libyui-gtk repo.
