### ISSUE TITLE
Need help with installation on Ubuntu 16.04

### ISSUE THREAD

**Issue by arjunmenon** [libyui/libyui#128]
Hey
Is this project active?
How do you install this in Ubuntu 16.04?
I can't try out the demo code.

**Comment by jreidinger** [comment]
Hi,
project is still alive. I use it regularly on openSUSE. Maybe someone who really use Ubuntu can help you with installation there.

**Comment by jreidinger** [comment]
I also modify a bit title, so any potential ubuntu user can help you.

**Comment by RexRegorum** [comment]
I am on Ubuntu 18.10 and am also having trouble. When I run 'rake osc:build', the script fails while attempting to log in with this error:

HTTPError: HTTP Error 401: Unauthorized
Server returned an error: HTTP Error 401: Unauthorized
Error getting meta for project 'devel%3Alibraries%3Alibyui' package 'libyui'

**Comment by jreidinger** [comment]
> I am on Ubuntu 18.10 and am also having trouble. When I run 'rake osc:build', the script fails while attempting to log in with this error:
> 
> HTTPError: HTTP Error 401: Unauthorized
> Server returned an error: HTTP Error 401: Unauthorized
> Error getting meta for project 'devel%3Alibraries%3Alibyui' package 'libyui'

It means that you need to setup your osc for building on open build service. But so far we are building there only for opensuse distro. But if anyone can provide ubuntu desc files, we can enable also build for ubuntu or debian. Just be aware that YaST team in suse support only openSUSE and SLE distribution building and for others, there are other maintainers.

**Comment by RexRegorum** [comment]
That makes sense. It looks like a minimal *.dsc file could be easy enough to provide so long as information such as the build dependencies and package maintainer contact line are available. A more complete file might contain options I would have no way to provide though. If there is a way I can provide those items, or maybe translate data from an OpenSUSE equivalent file, I would be glad to help. Is this as easy as running the debtransform tool from this site?

[](https://github.com/openSUSE/obs-build/blob/master/debtransform)

Thank you.

**Comment by lslezak** [comment]
In the past we built some packages for Ubuntu to be used at [Travis CI](https://travis-ci.org/).

See the `debian.*` files at https://github.com/yast/travis_old/tree/master_old/packages/libyui. See also https://github.com/yast/travis_old/blob/master/README.md, esp. the "Warnings" section.
