### ISSUE TITLE
Plugin SO version and load plugin

### ISSUE THREAD

**Issue by anaselli** [libyui/libyui#13]
I started removing old build-tools dependecy from gtk plugin, though i've realized loadplugin and pluginexists based plugin name and path on PLUGIN_SUFFIX that is of course the libyui one. 
New tree allows who is under it to find Version.cmake but external plugins need to know the so version outside. Have thought to a way to provide it?

I tried with cmake macros but i didn't seem to find anything but version at last.

**Comment by anaselli** [comment]
@mvidner I opened a [branch](https://github.com/anaselli/libyui-gtk/tree/NewLibyuiTree) to remove legacy buildtools dependency from libyui-gtk, following the changes we're discussing on issue #9. 
```
<off topic>
It isn't completed yet i've just ported basic features (missing docs for instance), we will discuss in a new PR maybe for that, but ycc and its tests iirc it is unused, could it be removed?
</off topic>

```
Branch can be built as in libyui document (build locally) or using make -f Makefile.repo
As plugins and modules usually don't need so version and come with name xxxx.so i didn't expect the strength check of so version on plugin name so i built with old Version.cmake in which so version was [0.0.0](https://github.com/anaselli/libyui-gtk/blob/NewLibyuiTree/VERSION.cmake#L6-L11) and where was written "These will be overridden from exports in LibyuiConfig.cmake" anyway.

Result plugin is  then:

> ll ~/TEST/lib64/yui/libyui-gtk*
> lrwxrwxrwx 1 anaselli anaselli      15 apr  7 19:48 /home/anaselli/TEST/lib64/yui/libyui-gtk.so -> libyui-gtk.so.0*
> lrwxrwxrwx 1 anaselli anaselli      19 apr  7 19:48 /home/anaselli/TEST/lib64/yui/libyui-gtk.so.0 -> libyui-gtk.so.0.0.0*
> -rwxr-xr-x 1 anaselli anaselli 5866552 apr  9 19:34 /home/anaselli/TEST/lib64/yui/libyui-gtk.so.0.0.0*
> 

Let's run HelloWorld forcing gtk from libyui/build/example (_./HelloWorld --gtk_):

```
./HelloWorld --gtk
<_M_> [ui] YUILoader.cc:60 loadUI(): DISPLAY: ":0"
<_M_> [ui] YUILoader.cc:61 loadUI(): XDG_CURRENT_DESKTOP: "KDE"
<_M_> [ui] YUILoader.cc:62 loadUI(): YUI_PREFERED_BACKEND: ""
<_M_> [ui] YUILoader.cc:96 loadUI(): User-selected UI-plugin: "gtk"
<ERR> [ui] YUILoader.cc:341 pluginExists(): Pathname not found libyui-gtk.so.15
<_M_> [ui] YUILoader.cc:342 pluginExists(): UI plugin /home/anaselli/TEST/lib64/yui/libyui-gtk.so.15 does not exist
<_M_> [ui] YUILoader.cc:342 pluginExists(): UI plugin /home/anaselli/TEST/lib64/yui/libyui-ncurses.so.15 exists
<_M_> [ui] YUILoader.cc:342 pluginExists(): UI plugin /home/anaselli/TEST/lib64/yui/libyui-qt.so.15 exists
<_M_> [ui] YUILoader.cc:128 loadUI(): Using UI-plugin: "qt"
<_M_> [ui] YUI.cc:83 YUI(): This is libyui 4.2.0
<_M_> [ui] YUI.cc:84 YUI(): Creating UI without threads
<_M_> [qt-ui] YQUI.cc:107 YQUI(): This is libyui-qt 4.2.0
<_M_> [ui] YUI.cc:238 topmostConstructorHasFinished(): Running without threads
<_M_> [qt-styler] QY2Styler.cc:146 loadStyleSheet(): Couldn't open style sheet "/usr/share/libyui/theme/current/wizard/style.qss"
<_M_> [qt-ui] YQUI.cc:251 processCommandLineArgs(): Qt argument: ./HelloWorld
<_M_> [qt-ui] YQUI.cc:251 processCommandLineArgs(): Qt argument: --gtk
<_M_> [qt-ui] YQUI.cc:404 calcDefaultSize(): Default size: 1792 x 985
<_M_> [qt-ui] YQApplication.cc:96 YQApplication(): QIcon::themeName = 'breeze'
<_M_> [qt-ui] YQApplication.cc:151 loadPredefinedQtTranslations(): Selected language: it_IT
<_M_> [qt-ui] YQApplication.cc:171 loadPredefinedQtTranslations(): Loaded translations for predefined Qt dialogs for it_IT
<_M_> [qt-ui] YQUI.cc:228 initUI(): YQUI initialized. Thread ID: 0x0x7f5a0f054740
```
I changed YUILoader code to have the following output:
```
<ERR> [ui] YUILoader.cc:341 pluginExists(): Pathname not found libyui-gtk.so.15
<_M_> [ui] YUILoader.cc:342 pluginExists(): UI plugin /home/anaselli/TEST/lib64/yui/libyui-gtk.so.15 does not exist
<_M_> [ui] YUILoader.cc:342 pluginExists(): UI plugin /home/anaselli/TEST/lib64/yui/libyui-ncurses.so.15 exists
<_M_> [ui] YUILoader.cc:342 pluginExists(): UI plugin /home/anaselli/TEST/lib64/yui/libyui-qt.so.15 exists
```
First line is the problem Plugin pathname required is libyui-gtk.so.15, while compiled one is **libyui-gtk.so.0**. So if the so version is really needed it should be exported somehow in some cmake macro to be use (FindLibyui.cmake maybe?).

**Comment by mvidner** [comment]
OK, I see now, you need `LibyuiConfig.cmake` (installed to /usr/lib64/cmake/libyui/LibyuiConfig.cmake or wherever CMake finds it)

We have attempted to provide it, in https://github.com/libyui/libyui/commit/b34e95e75b264112869cc72a52e1f6740a1449a6, but that attempt is broken, installing a `Config.cmake.in` somewhere else. It seems we do need to bring back some code to make building libyui-gtk possible.

**Comment by anaselli** [comment]
@mvidner i don't know if there is a standard way to for that, need to check however I think the best place should be 
`${CMAKE_INSTALL_DATAROOTDIR}/cmake/Modules `
so that can be used by include for instance and found locally by adding 
`-DCMAKE_MODULE_PATH=$HOME/TEST/share/cmake/Modules to cmake into "local.sh"`

**Comment by mvidner** [comment]
In https://github.com/libyui/libyui-gtk/commit/2cddf1013113709ddba27f7226ceb2ea274d5ec1 I have used libyui.pc which since today includes the version variables, commit https://github.com/libyui/libyui/pull/14/commits/41afa9c4a540c1ac2e58bbd422aeab66b58a27e8 in https://github.com/libyui/libyui/pull/14 .

With the help of that `./HelloWorld --gtk` loads GTK but fails on not finding a boost function, that looks like an isolated libyui-gtk problem.

**Comment by anaselli** [comment]
libyui.pc could be a way too :) I will make some tests later in the evening... thanks

**Comment by anaselli** [comment]
@mvidner with https://github.com/anaselli/libyui-gtk/commit/69bb438fc7a12a9dbadceee87f87b1558e3afdb4 I should have fixed this issue, i need to add doc and test libyui-mga too though.

**Comment by mvidner** [comment]
#19 (merged) contains the fixes needed to run `./HelloWorld --gtk`

**Comment by ancorgs** [comment]
@anaselli Does #19 fix the issue in this side so this can be closed?

**Comment by anaselli** [comment]
It seems so. I'm cutting some useless things and next to ask for PR for libyui-gtk soon.
I'm starting to work on libyui-mga too. i will open new issues for it if any...
