### ISSUE TITLE
Clonning issue of libyui in yocto openEmbedded dunfell branch

### ISSUE THREAD

**Issue by arghyaBiswas05** [libyui/libyui#17]
according to meta-openembedded/meta-oe/recipes-graphics/libyui/libyui_3.6.0.bb the libyui code base need to checkout to "8459235919f592b1bc099ecf9a947cb6344b6fa5" commit id. 
But according to the latest codebase, there is no such commit id. as a result compilation issue. 

Please update the meta-openEmbedded repo as your codebase commit id.

** here is the log file for reference.

[log.do_fetch.txt](https://github.com/libyui/libyui/files/6292213/log.do_fetch.txt)

**Comment by shundhammer** [comment]
We restructured the libyui repos recently. For that SHA you probably want to use the [legacy repo](https://github.com/libyui/libyui-old).

**Comment by shundhammer** [comment]
See also:

- https://github.com/libyui/libyui-old/pull/178
- https://gist.github.com/shundhammer/2d2b9bcf4b62df5b139daeceec8283ab
- https://gist.github.com/shundhammer/d96a63a1cab8245d20c2e3556238a114
