### ISSUE TITLE
error: 'YApplicationPrivate' defined as a struct here but previously declared as a class [-Werror,-Wmismatched-tags]

### ISSUE THREAD

**Issue by dkovar** [libyui/libyui#33]
Trying to build on OS X.

bash-3.2# cd src
bash-3.2# grep YApplicationPrivate *
grep: CMakeFiles: Is a directory
YApplication.cc:struct YApplicationPrivate
YApplication.cc:    YApplicationPrivate()
YApplication.cc:    : priv( new YApplicationPrivate() )
YApplication.h:class YApplicationPrivate;
YApplication.h:    ImplPtr<YApplicationPrivate> priv;

**Comment by jreidinger** [comment]
patch is in https://github.com/libyui/libyui/pull/98

**Comment by mvidner** [comment]
Merged.
