### ISSUE TITLE
YUI WidgetFactory and OptionalWidgetFactory are not removed

### ISSUE THREAD

**Issue by anaselli** [libyui/libyui#65]
I could be wrong but factory are not removed in YUI code, i noticed that during the YExternalWidgets development.

Please close this if I'm wrong.

**Comment by shundhammer** [comment]
That is correct. They follow the singleton pattern. Destroying singleton entails risks if done wrong, so we intentionally did not do that. When the program exits, the C++ runtime libs will destroy all created objects anyway.
