### ISSUE TITLE
I can't use "getYMGAWidgetFactory" 

### ISSUE THREAD

**Issue by thunderbirdtr** [libyui/libyui#67]
https://github.com/libyui/libyui/blob/dabdcd9cc6a0058fd6966d7d2e19d508debcc0ac/libyui-bindings/swig/python/examples/mga-dialogs.py#L64

My Error was : AttributeError: module 'yui' has no attribute 'YMGAWidgetFactory'

And I can't find "getYMGAWidgetFactory" too 

Any suggestion or help ?

**Comment by shundhammer** [comment]
You'll need to build and install those, too for the examples using YMGA widgets:

- https://github.com/manatools/libyui-mga
- https://github.com/manatools/libyui-mga-qt
- https://github.com/manatools/libyui-mga-ncurses
- maybe also https://github.com/manatools/libyui-mga-gtk 

It's a bit unfortunate that examples using that are in this repository, but @anaselli and the developer community about those _manatools_ appear to be the main consumer of the Python bindings.

**Comment by anaselli** [comment]
well libyui-bindings must be rebuilt with libyui-mga installed too.
As far as i can say i still hope to get **YMGA_CBTable** into libyui called as you like so that we can rid of this problem once and for all.
