### ISSUE TITLE
Resizing issue needs to be fixed on gtk (application is dnf dragora)

### ISSUE THREAD

**Issue by dankmemermusic** [libyui/libyui#72]
![Screenshot_20220505_090417](https://user-images.githubusercontent.com/104856296/166940760-d0ef4338-0849-4eb7-a711-1c96a4f418d4.png)
This is the smallest it gets (vertically) this problem is only present on gtk.

**Comment by shundhammer** [comment]
Please notice that libyui-gtk lives in a separate GitHub repository: https://github.com/libyui/libyui-gtk
