### ISSUE TITLE
Fix libyui-qt-pkg to build with upcoming libzypp

### ISSUE THREAD

**Issue by mlandres** [libyui/libyui#78]
https://github.com/libyui/libyui/blob/b55bdf42c899af08ad29e0aaef76fc1063ccc857/libyui-qt-pkg/src/YQPackageSelector.cc#L1208-L1221

You should not rely on boost settings libzypp uses or used. We'd like to remove our `#include <boost/bind/bind.hpp>`s.
Please qualify the placeholder `_1` as `boost::placeholders::_1` or use `#define BOOST_BIND_GLOBAL_PLACEHOLDERS`.

Or use `std::bind`, `std::ref` and `std::placeholders::_1`.

OTOH if you don't like `std::for_each` at all - which is what the comment indicates - why don't you write
```  
    for ( const zypp::PoolItem & pi : pool )
        writer.addIf( pi );
```
zypp does not force you to use `<algorithm>`.

**Comment by lslezak** [comment]
A minimal fix has been applied in https://github.com/libyui/libyui/pull/79

@mlandres thanks for the notification!
