### ISSUE TITLE
Multithreaded handling in YUI

### ISSUE THREAD

**Issue by sgiurgiu** [libyui/libyui#79]
Hi,
I'm trying to write an application using YUI and it will have quite a few threads doing background work. What will be the best way to update the UI? Is it safe to call "setText" on a label (for example) from another thread? Or is it a big no-no (like in most/all other UI libraries)?

I've made a small test where I have a thread in a loop, something like this:

``` cpp
std::thread t([&](){
    int x= 0;
    while(!stop) {      
      label.setText("some another text: "+std::to_string(x));
      ++x;
      sleep(2);
    }
  });

while(true) {
     YEvent * event = mainDialog->waitForEvent();
    if ( event )
    {
               .............
    }
}
  stop = true;
  t.join();
  mainDialog->destroy();
```

This works fine in QT and GTK, the label updates its text every 2 seconds. However, in ncurses nothing happens until i send an keystroke event to the dialog.
Changing the event loop to:

``` cpp
  while ( true )
  {
    YEvent * event = mainDialog->waitForEvent(1000);
   ...
   mainDialog->recalcLayout();
  }   
```

works fine in ncurses as well.

Is this approach ok? Will I get bitten by the segfault monster down the line if i continue like this?
What is your recommendation/the best way to go about this?

Thank you.

**Comment by shundhammer** [comment]
Qt explicitly states that all GUI operations need to be done in the "UI thread", i.e. the main thread that is already there when the program is started. Since all those libyui widget operations directly call their Qt counterparts in the Qt UI, I fear that means that you'll have to update all widget properties in that main thread.
