### ISSUE TITLE
Tree Item Selection

### ISSUE THREAD

**Issue by mvidner** [libyui/libyui#86]
This is a more detailed description of the problem that #74 intends to fix:
"Managed YTreeItem first item selection (children were not searched but remeained as selected). Now as soon as an item or a child is found as selected all the other items are deselected."

**Comment by mvidner** [comment]
Related code in the particular UIs:
- ncurses: https://github.com/libyui/libyui-ncurses/issues/26
- gtk: https://github.com/anaselli/libyui-gtk/commit/934962ef962fc6bdb34c0fd61b8a4b7e5406b570 from https://github.com/libyui/libyui-gtk/pull/37 (already merged)
- qt: https://github.com/anaselli/libyui-qt/commit/1e6f277be2f8ff5b8c74f704abe740545958185e from https://github.com/libyui/libyui-qt/pull/21 (already merged)

**Comment by anaselli** [comment]
test case https://gist.github.com/anaselli/1ca17b78ef619e42c22e

**Comment by mvidner** [comment]
OK, so the test case has (as a subtree)
- Item 4
    - Item 2
    - Item 3

all of which receive `setSelected`. 

The patch in https://github.com/libyui/libyui-ncurses/issues/26 , https://gist.github.com/anaselli/10420056 , fixes the selection to go from the very first item, Item 1, to Item 3. That looks fine.

But those subitems have a comment "this selection is discarded as it is a child of a selected item" which only happens if https://github.com/anaselli/libyui/commit/5038695103d9dbc8816c1dd6e15ce559b5c41672 from #74 is in effect. Not selecting children of a selected parent is IMHO an entirely separate change in behavior and I don't see why it would be desirable.

Additionally, the ncurses patch has code for multiselection mode which we should test too.

**Comment by anaselli** [comment]
answering to :"Not selecting children of a selected parent is IMHO an entirely separate change in behavior and I don't see why it would be desirable." 
Well it isn't desirable, but i made a choice. when you selected an item now you in single selection mode, you choose one and remove others. The way is the last selection remove the ones before. (it's a choice). I chose to stop at first item to avoid going down through the trees, without known which one is the last, which branch and the right one to select. Stopping at the higher level it's easy and quick. 
Any other choice could be wrong as well... so better deciding that the higher in the tree wins and document it.

**Comment by anaselli** [comment]
Let's say in single selection mode, one and only one selection should be passed, we cannot prevent any developer mistake.
Other solution would remove all selection and select the new one, but costs with all that loops iirc...

**Comment by anaselli** [comment]
@mvidner concerning the multi-selection test, here a test case that shows my patch works properly:
https://gist.github.com/anaselli/883d6d96b86cd0f1d401

**Comment by anaselli** [comment]
again on comment to the changed behaviour. That is valid *only* if we add a selected item to a tree (SelectionWidget really) not if we select it at run-time, so just when we are building and/or filling the
widget. And in any case children were never selected before into the addItem, so it is a change, but
an improvement, not a different behaviour IMHO

**Comment by anaselli** [comment]
Just a note on this subject again.
The libyui patch is more or less this: 
https://github.com/anaselli/libyui/commit/14dc423e759e9c93689ce5f72727ed3888e13f1c
As you can see @mvidner i didn't change that much, just  called deselectAllItems before and then selected the item again to be sure that there can be one and only one item selected.

To find the selected item through it children i called (as it was before really) findSelectedItem, so if you don't like the way the selected item is extracted you should change *findSelectedItem* behaviour, so please consider my patch again :D

**Comment by mvidner** [comment]
The fixes were released as
- libyui-3.2.8
- libyui-ncurses-2.47.7
