### ISSUE TITLE
CMAKE_INSTALL_PREFIX feature broken

### ISSUE THREAD

**Issue by anaselli** [libyui/libyui#9]
CMAKE_INSTALL_PREFIX should allow a custom installation on the system, I, for instance, usually prefer to test all locally in my home (e.g. ~/local) instead of breaking anything on the system or using /usr/local.
According on [CMAKE_INSTALL_PREFIX documentation](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html) it also affects CMAKE_SYSTEM_PREFIX_PATH to get all working to find libraries and so on and so for...
So my cmake line was (from build directory)

`cmake  -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$HOME/local ../`

make work ok, but install:

> Install the project...
> -- Install configuration: "Debug"
> -- Installing: /usr/share/libyui/buildtools/BuildTreeSettings.cmake.in
> CMake Error at legacy-buildtools/cmake_install.cmake:54 (file):
>   file INSTALL cannot copy file
>   "/home/anaselli/src/libyui/libyui/libyui/legacy-buildtools/BuildTreeSettings.cmake.in"
>   to "/usr/share/libyui/buildtools/BuildTreeSettings.cmake.in": Permission
>   denied.
> Call Stack (most recent call first):
>   cmake_install.cmake:47 (include)
> 
> 
> make: *** [Makefile:105: install] Errore 1

I seem to have read here and there into cmakefile to use DESTDIR but that is not the right option, according to its [manual](https://cmake.org/cmake/help/latest/envvar/DESTDIR.html#envvar:DESTDIR) that should prepend destdir to prefix

**Comment by anaselli** [comment]
I've started a [branch](https://github.com/anaselli/libyui/tree/CMAKE_INSTALL_PREFIX) in witch i would like to discuss and hopefully to fix that. Thanks for any feedbacks and advices to make it working again

**Comment by shundhammer** [comment]
The main problem is that it goes much deeper than just installing to a different install directory: Plug-ins also need to be _loaded_ from a different directory, and that involves a lot more than something like `$LD_LIBRARY_PATH`. We discussed that internally in depth, and the conclusion is that it's error-prone and a lot of hassle, and there is very little benefit in return.

With that, there would again be that neverending cascade of variables that need to be used instead of clearly understandable paths in the .cmake files; that was one of the main reasons why we wanted to get rid of that convoluted old CMake setup. It was just impossible to figure out **what** variable to use where and what the content of a variable might be. The new setup emphasizes readability, thus maintainability.

The reason why nobody had touched that old CMake setup for so many years was that it was almost impossible to change anything without breaking a lot of stuff in other places.

**Comment by anaselli** [comment]
As far as i can say it worked enough for my testing, testing purpose is probably the main reasons of changing prefix, and  bindings worked well too.

**Comment by shundhammer** [comment]
It may have appeared to work, but if you look closely, you will find that it still loads the plug-ins from the system path, not from your CMAKE_INSTALL_PREFIX path.

**Comment by anaselli** [comment]
Well nope... I'm sure enough... mga MenuBar was not installed in the system when i developed it... 

If you tell me to consider my changes I'll go on and show that here as soon as possible. I don't have libyui menubar on system 

> ll /usr/include/yui/YMenu*
> -rw-r--r-- 1 root root 7384 giu  4  2020 /usr/include/yui/YMenuButton.h
> -rw-r--r-- 1 root root 2220 giu  4  2020 /usr/include/yui/YMenuItem.h
> 

I was moving with old libyui tree and stopped for the new one... but i have branches called CBTable, into [mga](https://github.com/manatools/libyui-mga/commits/CBTable) plugins and [dnfdragora](https://github.com/manatools/dnfdragora/compare/CBTable) in wich i was implementing new CBTable (not in the system) and moving the code to new YMenuBar

**Comment by shundhammer** [comment]
I just checked, and you are right: It does take CMAKE_INSTALL_DIR into account when loading a plug-in:

https://github.com/libyui/libyui/blob/master/libyui/src/YUIPlugin.cc#L75-L86

which uses the header generated from

https://github.com/libyui/libyui/blob/master/libyui/src/Libyui_config.h.in#L10

which indeed uses CMAKE_INSTALL_DIR. I stand corrected. ;-)

**Comment by anaselli** [comment]
I have just committed a fixing in my branch for that if you wanted to look at that..
I only tried Qt plugin but it worked pretty well

**Comment by shundhammer** [comment]
Still, that doesn't change the fact that completely replacing `/usr` with `/usr/local` does not work because we emphasized keeping things simple.

**But** you can prepend that complete path with something of your choice, i.e. install everything to, say, `/work/usr/...`. We needed this for RPM builds so we can prepend an RPM build path.

The effect is very much the same if you set up LD_LIBRARY_PATH and PATH correctly.

**Comment by anaselli** [comment]
But you (and I too) don't have to replace the /usr in production.... that is for developing/debugging or whatever purpose.
Certainly Suse doc directory is not the same of other distros so a standard CMAKE_INSTALL_PREFIX way should be wanted. I'm not sure hard coding /usr is the right way and neither that emphasized  the simplicity, as you saw for the case above you needed to look at the code and that didn't respect CMAKE_INSTALL_PREFIX.

To add more information here, the cmake mageia macro used in rpmbuild:

> rpm --eval "%cmake"
> 
>     
>   CFLAGS="${CFLAGS:--O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fasynchronous-unwind-tables}" ; export CFLAGS ; 
>   CXXFLAGS="${CXXFLAGS:--O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fasynchronous-unwind-tables}" ; export CXXFLAGS ; 
>   FFLAGS="${FFLAGS:--O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fasynchronous-unwind-tables }" ; export FFLAGS ; 
>   FCFLAGS="${FCFLAGS:--O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fasynchronous-unwind-tables }" ; export FCFLAGS ; 
>   LDFLAGS="${LDFLAGS:- -Wl,--as-needed -Wl,--no-undefined -Wl,-z,relro -Wl,-O1 -Wl,--build-id -Wl,--enable-new-dtags}" ; export LDFLAGS 
>     /usr/bin/cmake -Wno-dev \
>         -S . \
>         -B build \
>         -DCMAKE_INSTALL_PREFIX:PATH=/usr \
>         -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib64 \
>         -DCMAKE_INSTALL_LIBEXECDIR:PATH=/usr/libexec \
>         -DCMAKE_INSTALL_RUNSTATEDIR:PATH=/run \
>         -DCMAKE_INSTALL_SYSCONFDIR:PATH=/etc \
>         -DINCLUDE_INSTALL_DIR:PATH=/usr/include \
>         -DLIB_INSTALL_DIR:PATH=/usr/lib64 \
>         -DSYSCONF_INSTALL_DIR:PATH=/etc \
>         -DSHARE_INSTALL_PREFIX:PATH=/usr/share \
>         -DCMAKE_BUILD_TYPE=RelWithDebInfo \
>         -DCMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING="-DNDEBUG" \
>         -DCMAKE_C_FLAGS_RELWITHDEBINFO:STRING="-DNDEBUG" \
>         -DCMAKE_CXX_FLAGS_RELEASE:STRING="-DNDEBUG" \
>         -DCMAKE_C_FLAGS_RELEASE:STRING="-DNDEBUG" \
> %if "lib64" == "lib64" 
>         -DLIB_SUFFIX=64 \
> %endif 
>         -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
>         -DCMAKE_MODULE_LINKER_FLAGS="-Wl,--as-needed  -Wl,-z,relro -Wl,-O1 -Wl,--build-id -Wl,--enable-new-dtags" \
>         -DBUILD_SHARED_LIBS:BOOL=ON \
>         -DBUILD_STATIC_LIBS:BOOL=OFF

**Comment by shundhammer** [comment]
Since we will get rid of installing the docs (including the autodocs) anyway, the doc dir will not be an issue anymore. The only remaining place is the install dir for the libyui examples, and I don't see a need for installing these, either.

Please let's keep this simple and not reintroduce the previous horror of a variable for each and every path where nobody ever knows what it contains.

**Comment by Conan-Kudo** [comment]
While I'm somewhat okay with eliminating the autodocs (you'd better be prepared to offer online docs somewhere then!), I am disappointed that you are making this more complex by locking the install prefix to `/usr`.

Simply rationalizing everything on `GNUInstallDirs` properly would have accounted for everything and make things "simple" to support arbitrary prefixes.

**Comment by shundhammer** [comment]
Please read the extensive documentation that I wrote about all this so I don't have to repeat it in this issue tracker.

**Comment by anaselli** [comment]
Just for testing all local i've fixed also doc by now. Did not require that much... :) since docs are not important and they probably will be removed we can add or revert changes without any problems. Other changes though don't seem horrible and help me a lot to port all plugins to work with new tree. I have some problems in building Gtk atm, but will check it tomorrow. What i'd like to reach is to have:

- [ ]  libyui-gtk with its own CMakeLists.txt and managed if posible as libyui
- [ ] libyui-mga and its plugins with their own CMakeLists.txt too

That should help in removing old buildtools after (at least as far as concern mga and gtk plugins, don't know if there are other ones available) if you agree.

**Comment by mvidner** [comment]
@anaselli hi!
Thanks for pointing this out. As Stefan has said, we don't use this feature in our team, but I and other team members still think it is fine to include it.

Can you please make a (draft?) PR out of your branch so that we can start commenting specific parts?

Maybe it would help to add an automated smoke test for this feature into https://github.com/anaselli/libyui/blob/CMAKE_INSTALL_PREFIX/.github/workflows/ci.yml ?

How about copying [your comment about how to compile and run with CMAKE_INSTALL_PREFIX](https://github.com/libyui/libyui/issues/9#issuecomment-813351207) into an md file in https://github.com/anaselli/libyui/tree/CMAKE_INSTALL_PREFIX/libyui/doc ?

**Comment by anaselli** [comment]
Hi @mlandres 
Yes the idea is to ask for PR and add/remove/change what has to be. Although i need some tests more, even probably if not related. I started building libyui-gtk and the plugin loaded was always the qt one. 
There are two points more, maybe opening new issues for those:
1. configuring for debug building results in an optimized code (caused by add_compile_options( "-Os" )    # Optimize for size)
2. if we stay or fix my changes for doc building Readme/Makefile.repo must change accordingly 

I think  tonight i should be ready for a PR, so that we can work on it in the next few days... thanks

**Comment by anaselli** [comment]
@mvidner @shundhammer as requested i sent a premature PR to discuss and modify. I also wrote a [md](https://github.com/anaselli/libyui/blob/CMAKE_INSTALL_PREFIX/libyui/doc/local_install.md) file as requested, I'm not mother tongue so be patience... hope to have written all.
For the smoke test i don't know what to do really. I have to check and test libyui-bindings yet (i'd expect some changes there too) and finish external plugin porting to new tree...

**Comment by ancorgs** [comment]
@anaselli Does https://github.com/libyui/libyui/pull/19 fix this issue so it can be closed?

**Comment by anaselli** [comment]
It seems so. I'm cutting some useless things and next to ask for PR for libyui-gtk soon.
I'm starting to work on libyui-mga too. i will open new issues for it if any...
One question, if i remove my cmake_prefix PR/branch will we miss the discussion? What should i do?

**Comment by shundhammer** [comment]
I customarily delete my PR branches after they are merged, and the PR itself and the associated discussion remain.

**Comment by anaselli** [comment]
@shundhammer but my PR has not been merged, you just cherry picked some things...
I don't mind that much... but every thing started there :)

**Comment by shundhammer** [comment]
@anaselli : Yes, I understand. But as I wrote: Even if we close the PR without merging, and you delete your branch, the discussion will remain intact.

**Comment by anaselli** [comment]
hmm there are two things yet I'm investigating on...

1. Libyui_config.h it is included into libyui-gtk but maybe it isn't needed.
2. libyui.pc for cflags

If i change Cflags: -I${exec_prefix}/include -I${includedir} i don't need to make any linked directory to src into external plugins. That allows _#include <yui/XXXX.h>_ and _#include <XXXX.h>_ syntax.

**Comment by mvidner** [comment]
@anaselli OK, let's fix this round :smile: 

1. **Libyui_config.h**, It is still used in the sources of the core library. It  looks like we forgot to install it, will fix.
2. **\*.pc includedir**, yes, we should support _#include <yui/XXXX.h>_ and _#include <XXXX.h>_ but looking at other files in /usr/lib64/pkgconfig I think this way is more common:

```diff
--- a/libyui/pkgconfig/libyui.pc.in
+++ b/libyui/pkgconfig/libyui.pc.in
@@ -10,7 +10,7 @@ exec_prefix=${prefix}
 datarootdir=${exec_prefix}/share
 datadir=${datarootdir}/libyui
 libdir=${exec_prefix}/@CMAKE_INSTALL_LIBDIR@
-includedir=${exec_prefix}/include/yui
+includedir=${prefix}/include
 plugindir=${exec_prefix}/@CMAKE_INSTALL_DIR@yui
 
 soversion_major=@SONAME_MAJOR@
@@ -23,4 +23,4 @@ Version: @VERSION@
 Description: libyui - GUI-abstraction library
 Libs: -L${libdir} -lyui
 Libs.private: -ldl -lpthread
-Cflags: -I${includedir}
+Cflags: -I${includedir}/yui -I${includedir}
```

**Comment by shundhammer** [comment]
@mvidner: Actually, it was quite intentional to not install `Libyui_config.h`.

It was not used anywhere anymore outside of libyui/libyui/src, and there only in very few places. Do we really need it in libyui-gtk?

**Comment by anaselli** [comment]
@shundhammer indeed. I've already removed that. I haven't committed it though because i'm also trying to fix loadIcon.

**Comment by anaselli** [comment]
@mvidner and @shundhammer  there is a missing feature yet. To build mga-XX plugins i sometimes need to include their libyui-XX files where it was possible to extend or use "upstream" classes.
So something like it was in before is missing:

- [ ] libyui-gtk.pc (i'll take care of this)
- [ ] libyui-qt.pc
- [ ] libyui-ncurses.pc

**Comment by shundhammer** [comment]
Added libyui-qt.pc and libyui-ncurses.pc with PR #32 . Please test.

**Comment by anaselli** [comment]
> Added libyui-qt.pc and libyui-ncurses.pc with PR #32 . Please test.
Tested Qt and works, thanks! 
I will work on ncurses (which i don't expect failure) and binding tomorrow though.

**Comment by shundhammer** [comment]
PR #32 with libyui-qt.pc and libyui-ncurses.pc is now merged.

**Comment by shundhammer** [comment]
@anaselli, is there anything left to do here now? If not, let's close this issue.

**Comment by anaselli** [comment]
Agreed 👍 I opened an issue related to bindings, discussion go on there for the right topics thanks
