### ISSUE TITLE
Is there any package available for CentOS 6?

### ISSUE THREAD

**Issue by santosh0705** [libyui/libyui#90]
From where I can get the package for CentOS6.

**Comment by santosh0705** [comment]
I tried to make rpm from openness/rhel7/fedora srpm i'm getting below error:
In file included from /root/rpmbuild/BUILD/libyui-libyui-master-3.1.5/src/YUILog.h:34,
                 from /root/rpmbuild/BUILD/libyui-libyui-master-3.1.5/src/YUI.cc:39:
/root/rpmbuild/BUILD/libyui-libyui-master-3.1.5/src/ImplPtr.h:63: error: only declarations of constructors can be 'explicit'


my gcc version is 
c++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)

**Comment by anaselli** [comment]
Well you should try to build it from git first so that you can see if you have any trouble.
Then if you want to get an up to date rpm get the suse srpm and work on that :)
I would also ave a look at mageia packages they contain some additional features and bug fixing not yet included...

**Comment by santosh0705** [comment]
I tried with Suse srpm but got the same error as above while compiling. It seems like libyui does not support older version of gcc.

**Comment by anaselli** [comment]
I think your problem is this commit needed by newer boost version
https://github.com/libyui/libyui/commit/d10b04ff4690e5cf254a1881827b4b2018902c13
Try to revert it and see if you can build it
